export * from './cliente'
export * from './evento/variables_dispositivo'
export {
	variables,
	Variables,
	variableOrigen,
	VariableOrigen,
	variableCoordenadas,
	VariableCoordenadas,
	variableDispositivo,
	variableNavegador,
	variableAdquisicion,
	VariableAdquisicion,
	variablePago,
	VariablePago,
	variableTarjetaDePago,
	VariableTarjetaDePago,
	variablePrecio,
	VariablePrecio,
	variableReceptorDeFacturacion,
	VariableReceptorDeFacturacion,
	variableDestinatarioDeEnvio,
	VariableDestinatarioDeEnvio,
	variableDireccionPostal,
	VariableDireccionPostal,
	evento,
	Evento,
	resultadoDeEvento,
	resultadoVerificacion,
	grupoDeEntes,
	ente,
	verificacionDeEvento,
	resultadoDeVerificacionDeEvento
} from '@verifico/base-api'
